# Generated by Django 4.1.3 on 2022-11-10 01:05

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_review_creator_album_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='ppoi',
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to=store.models.image_rename),
        ),
    ]
