"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
import os
from configurations import Configuration
from configurations import values
from dotenv import load_dotenv

class Dev(Configuration):
    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent
    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
    load_dotenv(BASE_DIR / '.env')
    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = 'django-insecure-gy@chd!-n)@wasv445exdasdw$2y^e6aq0oz9b0!^w!bfwtw'

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = ['*']

    # Application definition

    INSTALLED_APPS = [
        'django.contrib.admin',
        'django.contrib.auth',
        'django.contrib.contenttypes',
        'django.contrib.sessions',
        'django.contrib.messages',
        'django.contrib.staticfiles',
        'django_celery_results',
        'django_celery_beat',
        'rest_framework',
        'rest_framework.authtoken',
        'rest_framework_simplejwt',
        'corsheaders',
        'djoser',
        'versatileimagefield',
        'store',
        'users',
        'orders',
    ]

    MIDDLEWARE = [
        'django.middleware.security.SecurityMiddleware',
        'django.contrib.sessions.middleware.SessionMiddleware',
        'corsheaders.middleware.CorsMiddleware',
        'django.middleware.common.CommonMiddleware',
        'django.middleware.csrf.CsrfViewMiddleware',
        'django.contrib.auth.middleware.AuthenticationMiddleware',
        'django.contrib.messages.middleware.MessageMiddleware',
        'django.middleware.clickjacking.XFrameOptionsMiddleware',
    ]

    ROOT_URLCONF = 'src.urls'

    TEMPLATES = [
        {
            'BACKEND': 'django.template.backends.django.DjangoTemplates',
            'DIRS': [BASE_DIR / 'templates'],
            'APP_DIRS': True,
            'OPTIONS': {
                'context_processors': [
                    'django.template.context_processors.debug',
                    'django.template.context_processors.request',
                    'django.contrib.auth.context_processors.auth',
                    'django.contrib.messages.context_processors.messages',
                ],
            },
        },
    ]

    WSGI_APPLICATION = 'src.wsgi.application'

    # Database
    # https://docs.djangoproject.com/en/4.0/ref/settings/#databases

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

    # Default user model
    AUTH_USER_MODEL = "users.CustomUser"

    # Default Authentication backend
    AUTHENTICATION_BACKENDS = ['users.backends.AuthenticationBackend']
    # Password validation
    # https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        },
        {
            'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/4.0/topics/i18n/

    LANGUAGE_CODE = 'en-us'

    TIME_ZONE = 'UTC'

    USE_I18N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/4.0/howto/static-files/

    STATIC_URL = 'static/'
    STATIC_ROOT = 'static/'
    # define where uploaded files are saved.
    MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
    # URL/path to serve media from.
    MEDIA_URL = '/media/'

    # Default primary key field type
    # https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

    # Log configurations
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
                "style": "{",
            },
        },
        "handlers": {
            "console": {
                "class": "logging.StreamHandler",
                "stream": "ext://sys.stdout",
                "formatter": "verbose",
            }
        },
        "root": {
            "handlers": ["console"],
            "level": "DEBUG",
        },
    }

    # Celery settings
    CELERY_RESULT_BACKEND = "django-db"
    CELERY_BROKER_URL = "redis://localhost:6379/0"

    # Email settings
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    ADMINS = [("Abdoo", "abdoohossamm@outlook.com")]
    CORS_ALLOWED_ORIGINS = [
        'http://localhost:8080'
    ]
    PAGINATION_PAGE_SIZE = 20
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.BasicAuthentication",
            "rest_framework.authentication.SessionAuthentication",
            "rest_framework.authentication.TokenAuthentication",
            "rest_framework_simplejwt.authentication.JWTAuthentication"
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticatedOrReadOnly"
        ],
        "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
        "PAGE_SIZE": PAGINATION_PAGE_SIZE,
        # "DEFAULT_FILTER_BACKENDS": [
        #     "django_filters.rest_framework.DjangoFilterBackend",
        #     'rest_framework.filters.OrderingFilter'
        # ],
    }

    DJOSER = {
        'SERIALIZERS': {
            'current_user': 'users.api.v1.serializers.CurrentUserSerializer',
        },
    }
    PAYPAL_MODE = os.environ.get("PAYPAL_MODE")
    PAYPAL_CLIENT_ID = os.environ.get('PAYPAL_CLIENT_ID')
    PAYPAL_CLIENT_SECRET = os.environ.get('PAYPAL_CLIENT_SECRET')


class Prod(Dev):
    DEBUG = int(os.environ.get('MAIN_DEBUG', 0))
    SECRET_KEY = os.environ.get('MAIN_SECRET_KEY')
    ALLOWED_HOSTS = os.environ.get('MAIN_ALLOWED_HOSTS', '').split()
    ADMINS = [("Abdoo", "abdoohossamm@outlook.com"), ("abdoohossamm", "kmabdo28@gmail.com")]
    DATABASES = {
        'default': {
            'ENGINE': f"django.db.backends.{os.environ.get('MAIN_DB_CONNECTION')}",
            'NAME': os.environ.get('MAIN_DB_DATABASE'),
            'USER': os.environ.get('MAIN_DB_USERNAME'),
            'PASSWORD': os.environ.get('MAIN_DB_PASSWORD'),
            'HOST': os.environ.get('MAIN_DB_HOST'),
            'PORT': os.environ.get('MAIN_DB_PORT')
        }
    }
    CELERY_RESULT_BACKEND = "django-db"
    CELERY_BROKER_URL = f"redis://{os.environ.get('MAIN_REDIS_HOST')}:{os.environ.get('MAIN_REDIS_PORT')}/0"
    CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split()
